FROM ruby:3.0.1-alpine

ENV APP_PATH /app
ENV BUNDLE_VERSION 2.2.15
ENV BUNDLE_PATH /user/local/bundle/gems
ENV TMP_PATH /tmp/
ENV RAILS_LOG_TO_SDOUT true
ENV RAILS_PORT 3000

# base install
RUN apk --update add build-base nodejs tzdata postgresql-dev postgresql-client libxslt-dev libxml2-dev imagemagick yarn

# navigate to app directory
WORKDIR $APP_PATH
COPY Gemfile ${APP_PATH}/Gemfile
COPY Gemfile.lock ${APP_PATH}/Gemfile.lock

RUN gem install bundler
RUN if [[ "$RAILS_ENV" == "production" ]]; then bundle install --without development test; else bundle install; fi

COPY . ${APP_PATH}
RUN yarn

COPY ./dev-docker-entrypoint.sh /usr/local/bin/dev-docker-entrypoint.sh
RUN chmod +x /usr/local/bin/dev-docker-entrypoint.sh

EXPOSE $RAILS_PORT
ENTRYPOINT ["sh","/usr/local/bin/dev-docker-entrypoint.sh"]
CMD ["bundle", "exec"]