FROM ruby:3.0.1-alpine

ENV APP_PATH /app
ENV BUNDLE_VERSION 2.2.15
ENV BUNDLE_PATH /user/local/bundle/gems
ENV TMP_PATH /tmp/
ENV RAILS_LOG_TO_SDOUT true
ENV RAILS_PORT 3001

# base install
RUN apk --update add build-base nodejs tzdata postgresql-dev postgresql-client libxslt-dev libxml2-dev imagemagick yarn

# navigate to app directory
WORKDIR $APP_PATH
ADD Gemfile $APP_PATH/Gemfile
ADD Gemfile.lock $APP_PATH/Gemfile.lock

RUN gem install bundler
ADD . $APP_PATH
RUN if [[ "$RAILS_ENV" == "production" ]]; then bundle install --without development test; else bundle install; fi
RUN yarn install --check-files

ADD ./dev-docker-entrypoint.sh /usr/local/bin/dev-docker-entrypoint.sh
RUN chmod +x /usr/local/bin/dev-docker-entrypoint.sh

EXPOSE $RAILS_PORT
ENTRYPOINT ["sh","/usr/local/bin/dev-docker-entrypoint.sh"]
CMD ["rails","server","-b","0.0.0.0"]
RUN RAILS_ENV=production bundle exec rake assets:precompile