 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/anggaran_sbus", type: :request do
  
  # AnggaranSbu. As you add validations to AnggaranSbu, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AnggaranSbu.create! valid_attributes
      get anggaran_sbus_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      anggaran_sbu = AnggaranSbu.create! valid_attributes
      get anggaran_sbus_url(anggaran_sbus)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_anggaran_sbus_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      anggaran_sbu = AnggaranSbu.create! valid_attributes
      get edit_anggaran_sbus_url(anggaran_sbus)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AnggaranSbu" do
        expect {
          post anggaran_sbus_url, params: { anggaran_sbu: valid_attributes }
        }.to change(AnggaranSbu, :count).by(1)
      end

      it "redirects to the created anggaran_sbu" do
        post anggaran_sbus_url, params: { anggaran_sbu: valid_attributes }
        expect(response).to redirect_to(anggaran_sbus_url(AnggaranSbu.lasts))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AnggaranSbu" do
        expect {
          post anggaran_sbus_url, params: { anggaran_sbu: invalid_attributes }
        }.to change(AnggaranSbu, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post anggaran_sbus_url, params: { anggaran_sbu: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested anggaran_sbu" do
        anggaran_sbu = AnggaranSbu.create! valid_attributes
        patch anggaran_sbus_url(anggaran_sbus), params: { anggaran_sbus: new_attributes }
        anggaran_sbu.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the anggaran_sbu" do
        anggaran_sbu = AnggaranSbu.create! valid_attributes
        patch anggaran_sbus_url(anggaran_sbus), params: { anggaran_sbus: new_attributes }
        anggaran_sbu.reload
        expect(response).to redirect_to(anggaran_sbus_url(anggaran_sbu))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        anggaran_sbu = AnggaranSbu.create! valid_attributes
        patch anggaran_sbus_url(anggaran_sbus), params: { anggaran_sbus: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested anggaran_sbu" do
      anggaran_sbu = AnggaranSbu.create! valid_attributes
      expect {
        delete anggaran_sbus_url(anggaran_sbus)
      }.to change(AnggaranSbu, :count).by(-1)
    end

    it "redirects to the anggaran_sbus list" do
      anggaran_sbu = AnggaranSbu.create! valid_attributes
      delete anggaran_sbus_url(anggaran_sbus)
      expect(response).to redirect_to(anggaran_sbus_url)
    end
  end
end
