 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/anggaran_sshes", type: :request do
  
  # AnggaranSsh. As you add validations to AnggaranSsh, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AnggaranSsh.create! valid_attributes
      get anggaran_sshes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      anggaran_ssh = AnggaranSsh.create! valid_attributes
      get anggaran_ssh_url(anggaran_ssh)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_anggaran_ssh_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      anggaran_ssh = AnggaranSsh.create! valid_attributes
      get edit_anggaran_ssh_url(anggaran_ssh)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AnggaranSsh" do
        expect {
          post anggaran_sshes_url, params: { anggaran_ssh: valid_attributes }
        }.to change(AnggaranSsh, :count).by(1)
      end

      it "redirects to the created anggaran_ssh" do
        post anggaran_sshes_url, params: { anggaran_ssh: valid_attributes }
        expect(response).to redirect_to(anggaran_ssh_url(AnggaranSsh.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AnggaranSsh" do
        expect {
          post anggaran_sshes_url, params: { anggaran_ssh: invalid_attributes }
        }.to change(AnggaranSsh, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post anggaran_sshes_url, params: { anggaran_ssh: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested anggaran_ssh" do
        anggaran_ssh = AnggaranSsh.create! valid_attributes
        patch anggaran_ssh_url(anggaran_ssh), params: { anggaran_ssh: new_attributes }
        anggaran_ssh.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the anggaran_ssh" do
        anggaran_ssh = AnggaranSsh.create! valid_attributes
        patch anggaran_ssh_url(anggaran_ssh), params: { anggaran_ssh: new_attributes }
        anggaran_ssh.reload
        expect(response).to redirect_to(anggaran_ssh_url(anggaran_ssh))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        anggaran_ssh = AnggaranSsh.create! valid_attributes
        patch anggaran_ssh_url(anggaran_ssh), params: { anggaran_ssh: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested anggaran_ssh" do
      anggaran_ssh = AnggaranSsh.create! valid_attributes
      expect {
        delete anggaran_ssh_url(anggaran_ssh)
      }.to change(AnggaranSsh, :count).by(-1)
    end

    it "redirects to the anggaran_sshes list" do
      anggaran_ssh = AnggaranSsh.create! valid_attributes
      delete anggaran_ssh_url(anggaran_ssh)
      expect(response).to redirect_to(anggaran_sshes_url)
    end
  end
end
