 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/anggaran_hspks", type: :request do
  
  # AnggaranHspk. As you add validations to AnggaranHspk, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AnggaranHspk.create! valid_attributes
      get anggaran_hspks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      anggaran_hspk = AnggaranHspk.create! valid_attributes
      get anggaran_hspk_url(anggaran_hspk)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_anggaran_hspk_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      anggaran_hspk = AnggaranHspk.create! valid_attributes
      get edit_anggaran_hspk_url(anggaran_hspk)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AnggaranHspk" do
        expect {
          post anggaran_hspks_url, params: { anggaran_hspk: valid_attributes }
        }.to change(AnggaranHspk, :count).by(1)
      end

      it "redirects to the created anggaran_hspk" do
        post anggaran_hspks_url, params: { anggaran_hspk: valid_attributes }
        expect(response).to redirect_to(anggaran_hspk_url(AnggaranHspk.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AnggaranHspk" do
        expect {
          post anggaran_hspks_url, params: { anggaran_hspk: invalid_attributes }
        }.to change(AnggaranHspk, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post anggaran_hspks_url, params: { anggaran_hspk: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested anggaran_hspk" do
        anggaran_hspk = AnggaranHspk.create! valid_attributes
        patch anggaran_hspk_url(anggaran_hspk), params: { anggaran_hspk: new_attributes }
        anggaran_hspk.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the anggaran_hspk" do
        anggaran_hspk = AnggaranHspk.create! valid_attributes
        patch anggaran_hspk_url(anggaran_hspk), params: { anggaran_hspk: new_attributes }
        anggaran_hspk.reload
        expect(response).to redirect_to(anggaran_hspk_url(anggaran_hspk))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        anggaran_hspk = AnggaranHspk.create! valid_attributes
        patch anggaran_hspk_url(anggaran_hspk), params: { anggaran_hspk: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested anggaran_hspk" do
      anggaran_hspk = AnggaranHspk.create! valid_attributes
      expect {
        delete anggaran_hspk_url(anggaran_hspk)
      }.to change(AnggaranHspk, :count).by(-1)
    end

    it "redirects to the anggaran_hspks list" do
      anggaran_hspk = AnggaranHspk.create! valid_attributes
      delete anggaran_hspk_url(anggaran_hspk)
      expect(response).to redirect_to(anggaran_hspks_url)
    end
  end
end
