require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/anggota_tims", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # AnggotaTim. As you add validations to AnggotaTim, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AnggotaTim.create! valid_attributes
      get anggota_tims_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      anggota_tim = AnggotaTim.create! valid_attributes
      get anggota_tim_url(anggota_tim)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_anggota_tim_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      anggota_tim = AnggotaTim.create! valid_attributes
      get edit_anggota_tim_url(anggota_tim)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AnggotaTim" do
        expect {
          post anggota_tims_url, params: { anggota_tim: valid_attributes }
        }.to change(AnggotaTim, :count).by(1)
      end

      it "redirects to the created anggota_tim" do
        post anggota_tims_url, params: { anggota_tim: valid_attributes }
        expect(response).to redirect_to(anggota_tim_url(AnggotaTim.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AnggotaTim" do
        expect {
          post anggota_tims_url, params: { anggota_tim: invalid_attributes }
        }.to change(AnggotaTim, :count).by(0)
      end

    
      it "renders a successful response (i.e. to display the 'new' template)" do
        post anggota_tims_url, params: { anggota_tim: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested anggota_tim" do
        anggota_tim = AnggotaTim.create! valid_attributes
        patch anggota_tim_url(anggota_tim), params: { anggota_tim: new_attributes }
        anggota_tim.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the anggota_tim" do
        anggota_tim = AnggotaTim.create! valid_attributes
        patch anggota_tim_url(anggota_tim), params: { anggota_tim: new_attributes }
        anggota_tim.reload
        expect(response).to redirect_to(anggota_tim_url(anggota_tim))
      end
    end

    context "with invalid parameters" do
    
      it "renders a successful response (i.e. to display the 'edit' template)" do
        anggota_tim = AnggotaTim.create! valid_attributes
        patch anggota_tim_url(anggota_tim), params: { anggota_tim: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested anggota_tim" do
      anggota_tim = AnggotaTim.create! valid_attributes
      expect {
        delete anggota_tim_url(anggota_tim)
      }.to change(AnggotaTim, :count).by(-1)
    end

    it "redirects to the anggota_tims list" do
      anggota_tim = AnggotaTim.create! valid_attributes
      delete anggota_tim_url(anggota_tim)
      expect(response).to redirect_to(anggota_tims_url)
    end
  end
end
