require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/crosscuttings", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Crosscutting. As you add validations to Crosscutting, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Crosscutting.create! valid_attributes
      get crosscuttings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      crosscutting = Crosscutting.create! valid_attributes
      get crosscutting_url(crosscutting)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_crosscutting_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      crosscutting = Crosscutting.create! valid_attributes
      get edit_crosscutting_url(crosscutting)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Crosscutting" do
        expect {
          post crosscuttings_url, params: { crosscutting: valid_attributes }
        }.to change(Crosscutting, :count).by(1)
      end

      it "redirects to the created crosscutting" do
        post crosscuttings_url, params: { crosscutting: valid_attributes }
        expect(response).to redirect_to(crosscutting_url(Crosscutting.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Crosscutting" do
        expect {
          post crosscuttings_url, params: { crosscutting: invalid_attributes }
        }.to change(Crosscutting, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post crosscuttings_url, params: { crosscutting: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested crosscutting" do
        crosscutting = Crosscutting.create! valid_attributes
        patch crosscutting_url(crosscutting), params: { crosscutting: new_attributes }
        crosscutting.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the crosscutting" do
        crosscutting = Crosscutting.create! valid_attributes
        patch crosscutting_url(crosscutting), params: { crosscutting: new_attributes }
        crosscutting.reload
        expect(response).to redirect_to(crosscutting_url(crosscutting))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        crosscutting = Crosscutting.create! valid_attributes
        patch crosscutting_url(crosscutting), params: { crosscutting: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested crosscutting" do
      crosscutting = Crosscutting.create! valid_attributes
      expect {
        delete crosscutting_url(crosscutting)
      }.to change(Crosscutting, :count).by(-1)
    end

    it "redirects to the crosscuttings list" do
      crosscutting = Crosscutting.create! valid_attributes
      delete crosscutting_url(crosscutting)
      expect(response).to redirect_to(crosscuttings_url)
    end
  end
end
