 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dasar_hukums", type: :request do
  
  # DasarHukum. As you add validations to DasarHukum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DasarHukum.create! valid_attributes
      get dasar_hukums_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      dasar_hukum = DasarHukum.create! valid_attributes
      get dasar_hukum_url(dasar_hukum)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_dasar_hukum_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      dasar_hukum = DasarHukum.create! valid_attributes
      get edit_dasar_hukum_url(dasar_hukum)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DasarHukum" do
        expect {
          post dasar_hukums_url, params: { dasar_hukum: valid_attributes }
        }.to change(DasarHukum, :count).by(1)
      end

      it "redirects to the created dasar_hukum" do
        post dasar_hukums_url, params: { dasar_hukum: valid_attributes }
        expect(response).to redirect_to(dasar_hukum_url(DasarHukum.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DasarHukum" do
        expect {
          post dasar_hukums_url, params: { dasar_hukum: invalid_attributes }
        }.to change(DasarHukum, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post dasar_hukums_url, params: { dasar_hukum: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dasar_hukum" do
        dasar_hukum = DasarHukum.create! valid_attributes
        patch dasar_hukum_url(dasar_hukum), params: { dasar_hukum: new_attributes }
        dasar_hukum.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the dasar_hukum" do
        dasar_hukum = DasarHukum.create! valid_attributes
        patch dasar_hukum_url(dasar_hukum), params: { dasar_hukum: new_attributes }
        dasar_hukum.reload
        expect(response).to redirect_to(dasar_hukum_url(dasar_hukum))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        dasar_hukum = DasarHukum.create! valid_attributes
        patch dasar_hukum_url(dasar_hukum), params: { dasar_hukum: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested dasar_hukum" do
      dasar_hukum = DasarHukum.create! valid_attributes
      expect {
        delete dasar_hukum_url(dasar_hukum)
      }.to change(DasarHukum, :count).by(-1)
    end

    it "redirects to the dasar_hukums list" do
      dasar_hukum = DasarHukum.create! valid_attributes
      delete dasar_hukum_url(dasar_hukum)
      expect(response).to redirect_to(dasar_hukums_url)
    end
  end
end
