 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/hukums", type: :request do
  
  # Hukum. As you add validations to Hukum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Hukum.create! valid_attributes
      get hukums_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      hukum = Hukum.create! valid_attributes
      get hukum_url(hukum)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_hukum_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      hukum = Hukum.create! valid_attributes
      get edit_hukum_url(hukum)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Hukum" do
        expect {
          post hukums_url, params: { hukum: valid_attributes }
        }.to change(Hukum, :count).by(1)
      end

      it "redirects to the created hukum" do
        post hukums_url, params: { hukum: valid_attributes }
        expect(response).to redirect_to(hukum_url(Hukum.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Hukum" do
        expect {
          post hukums_url, params: { hukum: invalid_attributes }
        }.to change(Hukum, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post hukums_url, params: { hukum: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested hukum" do
        hukum = Hukum.create! valid_attributes
        patch hukum_url(hukum), params: { hukum: new_attributes }
        hukum.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the hukum" do
        hukum = Hukum.create! valid_attributes
        patch hukum_url(hukum), params: { hukum: new_attributes }
        hukum.reload
        expect(response).to redirect_to(hukum_url(hukum))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        hukum = Hukum.create! valid_attributes
        patch hukum_url(hukum), params: { hukum: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested hukum" do
      hukum = Hukum.create! valid_attributes
      expect {
        delete hukum_url(hukum)
      }.to change(Hukum, :count).by(-1)
    end

    it "redirects to the hukums list" do
      hukum = Hukum.create! valid_attributes
      delete hukum_url(hukum)
      expect(response).to redirect_to(hukums_url)
    end
  end
end
