require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/inovasi_tims", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # InovasiTim. As you add validations to InovasiTim, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      InovasiTim.create! valid_attributes
      get inovasi_tims_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      inovasi_tim = InovasiTim.create! valid_attributes
      get inovasi_tim_url(inovasi_tim)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_inovasi_tim_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      inovasi_tim = InovasiTim.create! valid_attributes
      get edit_inovasi_tim_url(inovasi_tim)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new InovasiTim" do
        expect {
          post inovasi_tims_url, params: { inovasi_tim: valid_attributes }
        }.to change(InovasiTim, :count).by(1)
      end

      it "redirects to the created inovasi_tim" do
        post inovasi_tims_url, params: { inovasi_tim: valid_attributes }
        expect(response).to redirect_to(inovasi_tim_url(InovasiTim.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new InovasiTim" do
        expect {
          post inovasi_tims_url, params: { inovasi_tim: invalid_attributes }
        }.to change(InovasiTim, :count).by(0)
      end

    
      it "renders a successful response (i.e. to display the 'new' template)" do
        post inovasi_tims_url, params: { inovasi_tim: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested inovasi_tim" do
        inovasi_tim = InovasiTim.create! valid_attributes
        patch inovasi_tim_url(inovasi_tim), params: { inovasi_tim: new_attributes }
        inovasi_tim.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the inovasi_tim" do
        inovasi_tim = InovasiTim.create! valid_attributes
        patch inovasi_tim_url(inovasi_tim), params: { inovasi_tim: new_attributes }
        inovasi_tim.reload
        expect(response).to redirect_to(inovasi_tim_url(inovasi_tim))
      end
    end

    context "with invalid parameters" do
    
      it "renders a successful response (i.e. to display the 'edit' template)" do
        inovasi_tim = InovasiTim.create! valid_attributes
        patch inovasi_tim_url(inovasi_tim), params: { inovasi_tim: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested inovasi_tim" do
      inovasi_tim = InovasiTim.create! valid_attributes
      expect {
        delete inovasi_tim_url(inovasi_tim)
      }.to change(InovasiTim, :count).by(-1)
    end

    it "redirects to the inovasi_tims list" do
      inovasi_tim = InovasiTim.create! valid_attributes
      delete inovasi_tim_url(inovasi_tim)
      expect(response).to redirect_to(inovasi_tims_url)
    end
  end
end
