require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/isu_strategis_opds", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # IsuStrategisOpd. As you add validations to IsuStrategisOpd, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      IsuStrategisOpd.create! valid_attributes
      get isu_strategis_opds_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      isu_strategis_opd = IsuStrategisOpd.create! valid_attributes
      get isu_strategis_opd_url(isu_strategis_opd)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_isu_strategis_opd_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      isu_strategis_opd = IsuStrategisOpd.create! valid_attributes
      get edit_isu_strategis_opd_url(isu_strategis_opd)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new IsuStrategisOpd" do
        expect {
          post isu_strategis_opds_url, params: { isu_strategis_opd: valid_attributes }
        }.to change(IsuStrategisOpd, :count).by(1)
      end

      it "redirects to the created isu_strategis_opd" do
        post isu_strategis_opds_url, params: { isu_strategis_opd: valid_attributes }
        expect(response).to redirect_to(isu_strategis_opd_url(IsuStrategisOpd.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new IsuStrategisOpd" do
        expect {
          post isu_strategis_opds_url, params: { isu_strategis_opd: invalid_attributes }
        }.to change(IsuStrategisOpd, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post isu_strategis_opds_url, params: { isu_strategis_opd: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested isu_strategis_opd" do
        isu_strategis_opd = IsuStrategisOpd.create! valid_attributes
        patch isu_strategis_opd_url(isu_strategis_opd), params: { isu_strategis_opd: new_attributes }
        isu_strategis_opd.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the isu_strategis_opd" do
        isu_strategis_opd = IsuStrategisOpd.create! valid_attributes
        patch isu_strategis_opd_url(isu_strategis_opd), params: { isu_strategis_opd: new_attributes }
        isu_strategis_opd.reload
        expect(response).to redirect_to(isu_strategis_opd_url(isu_strategis_opd))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        isu_strategis_opd = IsuStrategisOpd.create! valid_attributes
        patch isu_strategis_opd_url(isu_strategis_opd), params: { isu_strategis_opd: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested isu_strategis_opd" do
      isu_strategis_opd = IsuStrategisOpd.create! valid_attributes
      expect {
        delete isu_strategis_opd_url(isu_strategis_opd)
      }.to change(IsuStrategisOpd, :count).by(-1)
    end

    it "redirects to the isu_strategis_opds list" do
      isu_strategis_opd = IsuStrategisOpd.create! valid_attributes
      delete isu_strategis_opd_url(isu_strategis_opd)
      expect(response).to redirect_to(isu_strategis_opds_url)
    end
  end
end
