require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/jabatans", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Jabatan. As you add validations to Jabatan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Jabatan.create! valid_attributes
      get jabatans_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      jabatan = Jabatan.create! valid_attributes
      get jabatan_url(jabatan)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_jabatan_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      jabatan = Jabatan.create! valid_attributes
      get edit_jabatan_url(jabatan)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Jabatan" do
        expect {
          post jabatans_url, params: { jabatan: valid_attributes }
        }.to change(Jabatan, :count).by(1)
      end

      it "redirects to the created jabatan" do
        post jabatans_url, params: { jabatan: valid_attributes }
        expect(response).to redirect_to(jabatan_url(Jabatan.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Jabatan" do
        expect {
          post jabatans_url, params: { jabatan: invalid_attributes }
        }.to change(Jabatan, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post jabatans_url, params: { jabatan: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested jabatan" do
        jabatan = Jabatan.create! valid_attributes
        patch jabatan_url(jabatan), params: { jabatan: new_attributes }
        jabatan.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the jabatan" do
        jabatan = Jabatan.create! valid_attributes
        patch jabatan_url(jabatan), params: { jabatan: new_attributes }
        jabatan.reload
        expect(response).to redirect_to(jabatan_url(jabatan))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        jabatan = Jabatan.create! valid_attributes
        patch jabatan_url(jabatan), params: { jabatan: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested jabatan" do
      jabatan = Jabatan.create! valid_attributes
      expect {
        delete jabatan_url(jabatan)
      }.to change(Jabatan, :count).by(-1)
    end

    it "redirects to the jabatans list" do
      jabatan = Jabatan.create! valid_attributes
      delete jabatan_url(jabatan)
      expect(response).to redirect_to(jabatans_url)
    end
  end
end
