require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/kebutuhans", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Kebutuhan. As you add validations to Kebutuhan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Kebutuhan.create! valid_attributes
      get kebutuhans_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      kebutuhan = Kebutuhan.create! valid_attributes
      get kebutuhan_url(kebutuhan)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_kebutuhan_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      kebutuhan = Kebutuhan.create! valid_attributes
      get edit_kebutuhan_url(kebutuhan)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Kebutuhan" do
        expect {
          post kebutuhans_url, params: { kebutuhan: valid_attributes }
        }.to change(Kebutuhan, :count).by(1)
      end

      it "redirects to the created kebutuhan" do
        post kebutuhans_url, params: { kebutuhan: valid_attributes }
        expect(response).to redirect_to(kebutuhan_url(Kebutuhan.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Kebutuhan" do
        expect {
          post kebutuhans_url, params: { kebutuhan: invalid_attributes }
        }.to change(Kebutuhan, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post kebutuhans_url, params: { kebutuhan: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested kebutuhan" do
        kebutuhan = Kebutuhan.create! valid_attributes
        patch kebutuhan_url(kebutuhan), params: { kebutuhan: new_attributes }
        kebutuhan.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the kebutuhan" do
        kebutuhan = Kebutuhan.create! valid_attributes
        patch kebutuhan_url(kebutuhan), params: { kebutuhan: new_attributes }
        kebutuhan.reload
        expect(response).to redirect_to(kebutuhan_url(kebutuhan))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        kebutuhan = Kebutuhan.create! valid_attributes
        patch kebutuhan_url(kebutuhan), params: { kebutuhan: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested kebutuhan" do
      kebutuhan = Kebutuhan.create! valid_attributes
      expect {
        delete kebutuhan_url(kebutuhan)
      }.to change(Kebutuhan, :count).by(-1)
    end

    it "redirects to the kebutuhans list" do
      kebutuhan = Kebutuhan.create! valid_attributes
      delete kebutuhan_url(kebutuhan)
      expect(response).to redirect_to(kebutuhans_url)
    end
  end
end
