 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/koefisiens", type: :request do
  
  # Koefisien. As you add validations to Koefisien, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Koefisien.create! valid_attributes
      get koefisiens_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      koefisien = Koefisien.create! valid_attributes
      get koefisien_url(koefisien)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_koefisien_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      koefisien = Koefisien.create! valid_attributes
      get edit_koefisien_url(koefisien)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Koefisien" do
        expect {
          post koefisiens_url, params: { koefisien: valid_attributes }
        }.to change(Koefisien, :count).by(1)
      end

      it "redirects to the created koefisien" do
        post koefisiens_url, params: { koefisien: valid_attributes }
        expect(response).to redirect_to(koefisien_url(Koefisien.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Koefisien" do
        expect {
          post koefisiens_url, params: { koefisien: invalid_attributes }
        }.to change(Koefisien, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post koefisiens_url, params: { koefisien: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested koefisien" do
        koefisien = Koefisien.create! valid_attributes
        patch koefisien_url(koefisien), params: { koefisien: new_attributes }
        koefisien.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the koefisien" do
        koefisien = Koefisien.create! valid_attributes
        patch koefisien_url(koefisien), params: { koefisien: new_attributes }
        koefisien.reload
        expect(response).to redirect_to(koefisien_url(koefisien))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        koefisien = Koefisien.create! valid_attributes
        patch koefisien_url(koefisien), params: { koefisien: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested koefisien" do
      koefisien = Koefisien.create! valid_attributes
      expect {
        delete koefisien_url(koefisien)
      }.to change(Koefisien, :count).by(-1)
    end

    it "redirects to the koefisiens list" do
      koefisien = Koefisien.create! valid_attributes
      delete koefisien_url(koefisien)
      expect(response).to redirect_to(koefisiens_url)
    end
  end
end
