require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/kolabs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Kolab. As you add validations to Kolab, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Kolab.create! valid_attributes
      get kolabs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      kolab = Kolab.create! valid_attributes
      get kolab_url(kolab)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_kolab_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      kolab = Kolab.create! valid_attributes
      get edit_kolab_url(kolab)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Kolab" do
        expect {
          post kolabs_url, params: { kolab: valid_attributes }
        }.to change(Kolab, :count).by(1)
      end

      it "redirects to the created kolab" do
        post kolabs_url, params: { kolab: valid_attributes }
        expect(response).to redirect_to(kolab_url(Kolab.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Kolab" do
        expect {
          post kolabs_url, params: { kolab: invalid_attributes }
        }.to change(Kolab, :count).by(0)
      end

    
      it "renders a successful response (i.e. to display the 'new' template)" do
        post kolabs_url, params: { kolab: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested kolab" do
        kolab = Kolab.create! valid_attributes
        patch kolab_url(kolab), params: { kolab: new_attributes }
        kolab.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the kolab" do
        kolab = Kolab.create! valid_attributes
        patch kolab_url(kolab), params: { kolab: new_attributes }
        kolab.reload
        expect(response).to redirect_to(kolab_url(kolab))
      end
    end

    context "with invalid parameters" do
    
      it "renders a successful response (i.e. to display the 'edit' template)" do
        kolab = Kolab.create! valid_attributes
        patch kolab_url(kolab), params: { kolab: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested kolab" do
      kolab = Kolab.create! valid_attributes
      expect {
        delete kolab_url(kolab)
      }.to change(Kolab, :count).by(-1)
    end

    it "redirects to the kolabs list" do
      kolab = Kolab.create! valid_attributes
      delete kolab_url(kolab)
      expect(response).to redirect_to(kolabs_url)
    end
  end
end
