require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/kuncis", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Kunci. As you add validations to Kunci, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Kunci.create! valid_attributes
      get kuncis_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      kunci = Kunci.create! valid_attributes
      get kunci_url(kunci)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_kunci_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      kunci = Kunci.create! valid_attributes
      get edit_kunci_url(kunci)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Kunci" do
        expect {
          post kuncis_url, params: { kunci: valid_attributes }
        }.to change(Kunci, :count).by(1)
      end

      it "redirects to the created kunci" do
        post kuncis_url, params: { kunci: valid_attributes }
        expect(response).to redirect_to(kunci_url(Kunci.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Kunci" do
        expect {
          post kuncis_url, params: { kunci: invalid_attributes }
        }.to change(Kunci, :count).by(0)
      end

    
      it "renders a successful response (i.e. to display the 'new' template)" do
        post kuncis_url, params: { kunci: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested kunci" do
        kunci = Kunci.create! valid_attributes
        patch kunci_url(kunci), params: { kunci: new_attributes }
        kunci.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the kunci" do
        kunci = Kunci.create! valid_attributes
        patch kunci_url(kunci), params: { kunci: new_attributes }
        kunci.reload
        expect(response).to redirect_to(kunci_url(kunci))
      end
    end

    context "with invalid parameters" do
    
      it "renders a successful response (i.e. to display the 'edit' template)" do
        kunci = Kunci.create! valid_attributes
        patch kunci_url(kunci), params: { kunci: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested kunci" do
      kunci = Kunci.create! valid_attributes
      expect {
        delete kunci_url(kunci)
      }.to change(Kunci, :count).by(-1)
    end

    it "redirects to the kuncis list" do
      kunci = Kunci.create! valid_attributes
      delete kunci_url(kunci)
      expect(response).to redirect_to(kuncis_url)
    end
  end
end
