 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/mandatoris", type: :request do
  
  # Mandatori. As you add validations to Mandatori, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Mandatori.create! valid_attributes
      get mandatoris_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      mandatori = Mandatori.create! valid_attributes
      get mandatori_url(mandatori)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_mandatori_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      mandatori = Mandatori.create! valid_attributes
      get edit_mandatori_url(mandatori)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Mandatori" do
        expect {
          post mandatoris_url, params: { mandatori: valid_attributes }
        }.to change(Mandatori, :count).by(1)
      end

      it "redirects to the created mandatori" do
        post mandatoris_url, params: { mandatori: valid_attributes }
        expect(response).to redirect_to(mandatori_url(Mandatori.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Mandatori" do
        expect {
          post mandatoris_url, params: { mandatori: invalid_attributes }
        }.to change(Mandatori, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post mandatoris_url, params: { mandatori: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mandatori" do
        mandatori = Mandatori.create! valid_attributes
        patch mandatori_url(mandatori), params: { mandatori: new_attributes }
        mandatori.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the mandatori" do
        mandatori = Mandatori.create! valid_attributes
        patch mandatori_url(mandatori), params: { mandatori: new_attributes }
        mandatori.reload
        expect(response).to redirect_to(mandatori_url(mandatori))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        mandatori = Mandatori.create! valid_attributes
        patch mandatori_url(mandatori), params: { mandatori: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested mandatori" do
      mandatori = Mandatori.create! valid_attributes
      expect {
        delete mandatori_url(mandatori)
      }.to change(Mandatori, :count).by(-1)
    end

    it "redirects to the mandatoris list" do
      mandatori = Mandatori.create! valid_attributes
      delete mandatori_url(mandatori)
      expect(response).to redirect_to(mandatoris_url)
    end
  end
end
