require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/misis", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Misi. As you add validations to Misi, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Misi.create! valid_attributes
      get misis_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      misi = Misi.create! valid_attributes
      get misi_url(misi)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_misi_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      misi = Misi.create! valid_attributes
      get edit_misi_url(misi)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Misi" do
        expect {
          post misis_url, params: { misi: valid_attributes }
        }.to change(Misi, :count).by(1)
      end

      it "redirects to the created misi" do
        post misis_url, params: { misi: valid_attributes }
        expect(response).to redirect_to(misi_url(Misi.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Misi" do
        expect {
          post misis_url, params: { misi: invalid_attributes }
        }.to change(Misi, :count).by(0)
      end

    
      it "renders a successful response (i.e. to display the 'new' template)" do
        post misis_url, params: { misi: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested misi" do
        misi = Misi.create! valid_attributes
        patch misi_url(misi), params: { misi: new_attributes }
        misi.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the misi" do
        misi = Misi.create! valid_attributes
        patch misi_url(misi), params: { misi: new_attributes }
        misi.reload
        expect(response).to redirect_to(misi_url(misi))
      end
    end

    context "with invalid parameters" do
    
      it "renders a successful response (i.e. to display the 'edit' template)" do
        misi = Misi.create! valid_attributes
        patch misi_url(misi), params: { misi: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested misi" do
      misi = Misi.create! valid_attributes
      expect {
        delete misi_url(misi)
      }.to change(Misi, :count).by(-1)
    end

    it "redirects to the misis list" do
      misi = Misi.create! valid_attributes
      delete misi_url(misi)
      expect(response).to redirect_to(misis_url)
    end
  end
end
