require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/opd_bidangs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # OpdBidang. As you add validations to OpdBidang, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      OpdBidang.create! valid_attributes
      get opd_bidangs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      opd_bidang = OpdBidang.create! valid_attributes
      get opd_bidang_url(opd_bidang)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_opd_bidang_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      opd_bidang = OpdBidang.create! valid_attributes
      get edit_opd_bidang_url(opd_bidang)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OpdBidang" do
        expect {
          post opd_bidangs_url, params: { opd_bidang: valid_attributes }
        }.to change(OpdBidang, :count).by(1)
      end

      it "redirects to the created opd_bidang" do
        post opd_bidangs_url, params: { opd_bidang: valid_attributes }
        expect(response).to redirect_to(opd_bidang_url(OpdBidang.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OpdBidang" do
        expect {
          post opd_bidangs_url, params: { opd_bidang: invalid_attributes }
        }.to change(OpdBidang, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post opd_bidangs_url, params: { opd_bidang: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested opd_bidang" do
        opd_bidang = OpdBidang.create! valid_attributes
        patch opd_bidang_url(opd_bidang), params: { opd_bidang: new_attributes }
        opd_bidang.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the opd_bidang" do
        opd_bidang = OpdBidang.create! valid_attributes
        patch opd_bidang_url(opd_bidang), params: { opd_bidang: new_attributes }
        opd_bidang.reload
        expect(response).to redirect_to(opd_bidang_url(opd_bidang))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        opd_bidang = OpdBidang.create! valid_attributes
        patch opd_bidang_url(opd_bidang), params: { opd_bidang: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested opd_bidang" do
      opd_bidang = OpdBidang.create! valid_attributes
      expect {
        delete opd_bidang_url(opd_bidang)
      }.to change(OpdBidang, :count).by(-1)
    end

    it "redirects to the opd_bidangs list" do
      opd_bidang = OpdBidang.create! valid_attributes
      delete opd_bidang_url(opd_bidang)
      expect(response).to redirect_to(opd_bidangs_url)
    end
  end
end
