 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/pagus", type: :request do
  
  # Pagu. As you add validations to Pagu, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Pagu.create! valid_attributes
      get pagus_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      pagu = Pagu.create! valid_attributes
      get pagu_url(pagu)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_pagu_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      pagu = Pagu.create! valid_attributes
      get edit_pagu_url(pagu)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Pagu" do
        expect {
          post pagus_url, params: { pagu: valid_attributes }
        }.to change(Pagu, :count).by(1)
      end

      it "redirects to the created pagu" do
        post pagus_url, params: { pagu: valid_attributes }
        expect(response).to redirect_to(pagu_url(Pagu.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Pagu" do
        expect {
          post pagus_url, params: { pagu: invalid_attributes }
        }.to change(Pagu, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post pagus_url, params: { pagu: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pagu" do
        pagu = Pagu.create! valid_attributes
        patch pagu_url(pagu), params: { pagu: new_attributes }
        pagu.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the pagu" do
        pagu = Pagu.create! valid_attributes
        patch pagu_url(pagu), params: { pagu: new_attributes }
        pagu.reload
        expect(response).to redirect_to(pagu_url(pagu))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        pagu = Pagu.create! valid_attributes
        patch pagu_url(pagu), params: { pagu: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested pagu" do
      pagu = Pagu.create! valid_attributes
      expect {
        delete pagu_url(pagu)
      }.to change(Pagu, :count).by(-1)
    end

    it "redirects to the pagus list" do
      pagu = Pagu.create! valid_attributes
      delete pagu_url(pagu)
      expect(response).to redirect_to(pagus_url)
    end
  end
end
