 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/pajaks", type: :request do
  
  # Pajak. As you add validations to Pajak, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Pajak.create! valid_attributes
      get pajaks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      pajak = Pajak.create! valid_attributes
      get pajak_url(pajak)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_pajak_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      pajak = Pajak.create! valid_attributes
      get edit_pajak_url(pajak)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Pajak" do
        expect {
          post pajaks_url, params: { pajak: valid_attributes }
        }.to change(Pajak, :count).by(1)
      end

      it "redirects to the created pajak" do
        post pajaks_url, params: { pajak: valid_attributes }
        expect(response).to redirect_to(pajak_url(Pajak.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Pajak" do
        expect {
          post pajaks_url, params: { pajak: invalid_attributes }
        }.to change(Pajak, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post pajaks_url, params: { pajak: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pajak" do
        pajak = Pajak.create! valid_attributes
        patch pajak_url(pajak), params: { pajak: new_attributes }
        pajak.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the pajak" do
        pajak = Pajak.create! valid_attributes
        patch pajak_url(pajak), params: { pajak: new_attributes }
        pajak.reload
        expect(response).to redirect_to(pajak_url(pajak))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        pajak = Pajak.create! valid_attributes
        patch pajak_url(pajak), params: { pajak: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested pajak" do
      pajak = Pajak.create! valid_attributes
      expect {
        delete pajak_url(pajak)
      }.to change(Pajak, :count).by(-1)
    end

    it "redirects to the pajaks list" do
      pajak = Pajak.create! valid_attributes
      delete pajak_url(pajak)
      expect(response).to redirect_to(pajaks_url)
    end
  end
end
