require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/periodes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Periode. As you add validations to Periode, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Periode.create! valid_attributes
      get periodes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      periode = Periode.create! valid_attributes
      get periode_url(periode)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_periode_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      periode = Periode.create! valid_attributes
      get edit_periode_url(periode)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Periode" do
        expect {
          post periodes_url, params: { periode: valid_attributes }
        }.to change(Periode, :count).by(1)
      end

      it "redirects to the created periode" do
        post periodes_url, params: { periode: valid_attributes }
        expect(response).to redirect_to(periode_url(Periode.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Periode" do
        expect {
          post periodes_url, params: { periode: invalid_attributes }
        }.to change(Periode, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post periodes_url, params: { periode: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested periode" do
        periode = Periode.create! valid_attributes
        patch periode_url(periode), params: { periode: new_attributes }
        periode.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the periode" do
        periode = Periode.create! valid_attributes
        patch periode_url(periode), params: { periode: new_attributes }
        periode.reload
        expect(response).to redirect_to(periode_url(periode))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        periode = Periode.create! valid_attributes
        patch periode_url(periode), params: { periode: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested periode" do
      periode = Periode.create! valid_attributes
      expect {
        delete periode_url(periode)
      }.to change(Periode, :count).by(-1)
    end

    it "redirects to the periodes list" do
      periode = Periode.create! valid_attributes
      delete periode_url(periode)
      expect(response).to redirect_to(periodes_url)
    end
  end
end
