require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/permasalahan_opds", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PermasalahanOpd. As you add validations to PermasalahanOpd, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PermasalahanOpd.create! valid_attributes
      get permasalahan_opds_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      permasalahan_opd = PermasalahanOpd.create! valid_attributes
      get permasalahan_opd_url(permasalahan_opd)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_permasalahan_opd_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      permasalahan_opd = PermasalahanOpd.create! valid_attributes
      get edit_permasalahan_opd_url(permasalahan_opd)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PermasalahanOpd" do
        expect {
          post permasalahan_opds_url, params: { permasalahan_opd: valid_attributes }
        }.to change(PermasalahanOpd, :count).by(1)
      end

      it "redirects to the created permasalahan_opd" do
        post permasalahan_opds_url, params: { permasalahan_opd: valid_attributes }
        expect(response).to redirect_to(permasalahan_opd_url(PermasalahanOpd.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PermasalahanOpd" do
        expect {
          post permasalahan_opds_url, params: { permasalahan_opd: invalid_attributes }
        }.to change(PermasalahanOpd, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post permasalahan_opds_url, params: { permasalahan_opd: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested permasalahan_opd" do
        permasalahan_opd = PermasalahanOpd.create! valid_attributes
        patch permasalahan_opd_url(permasalahan_opd), params: { permasalahan_opd: new_attributes }
        permasalahan_opd.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the permasalahan_opd" do
        permasalahan_opd = PermasalahanOpd.create! valid_attributes
        patch permasalahan_opd_url(permasalahan_opd), params: { permasalahan_opd: new_attributes }
        permasalahan_opd.reload
        expect(response).to redirect_to(permasalahan_opd_url(permasalahan_opd))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        permasalahan_opd = PermasalahanOpd.create! valid_attributes
        patch permasalahan_opd_url(permasalahan_opd), params: { permasalahan_opd: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested permasalahan_opd" do
      permasalahan_opd = PermasalahanOpd.create! valid_attributes
      expect {
        delete permasalahan_opd_url(permasalahan_opd)
      }.to change(PermasalahanOpd, :count).by(-1)
    end

    it "redirects to the permasalahan_opds list" do
      permasalahan_opd = PermasalahanOpd.create! valid_attributes
      delete permasalahan_opd_url(permasalahan_opd)
      expect(response).to redirect_to(permasalahan_opds_url)
    end
  end
end
