require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/permasalahans", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Permasalahan. As you add validations to Permasalahan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Permasalahan.create! valid_attributes
      get permasalahans_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      permasalahan = Permasalahan.create! valid_attributes
      get permasalahan_url(permasalahan)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_permasalahan_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      permasalahan = Permasalahan.create! valid_attributes
      get edit_permasalahan_url(permasalahan)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Permasalahan" do
        expect {
          post permasalahans_url, params: { permasalahan: valid_attributes }
        }.to change(Permasalahan, :count).by(1)
      end

      it "redirects to the created permasalahan" do
        post permasalahans_url, params: { permasalahan: valid_attributes }
        expect(response).to redirect_to(permasalahan_url(Permasalahan.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Permasalahan" do
        expect {
          post permasalahans_url, params: { permasalahan: invalid_attributes }
        }.to change(Permasalahan, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post permasalahans_url, params: { permasalahan: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested permasalahan" do
        permasalahan = Permasalahan.create! valid_attributes
        patch permasalahan_url(permasalahan), params: { permasalahan: new_attributes }
        permasalahan.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the permasalahan" do
        permasalahan = Permasalahan.create! valid_attributes
        patch permasalahan_url(permasalahan), params: { permasalahan: new_attributes }
        permasalahan.reload
        expect(response).to redirect_to(permasalahan_url(permasalahan))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        permasalahan = Permasalahan.create! valid_attributes
        patch permasalahan_url(permasalahan), params: { permasalahan: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested permasalahan" do
      permasalahan = Permasalahan.create! valid_attributes
      expect {
        delete permasalahan_url(permasalahan)
      }.to change(Permasalahan, :count).by(-1)
    end

    it "redirects to the permasalahans list" do
      permasalahan = Permasalahan.create! valid_attributes
      delete permasalahan_url(permasalahan)
      expect(response).to redirect_to(permasalahans_url)
    end
  end
end
