require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/pindah_pohon_kinerjas", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PindahPohonKinerja. As you add validations to PindahPohonKinerja, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PindahPohonKinerja.create! valid_attributes
      get pindah_pohon_kinerjas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      pindah_pohon_kinerja = PindahPohonKinerja.create! valid_attributes
      get pindah_pohon_kinerja_url(pindah_pohon_kinerja)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_pindah_pohon_kinerja_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      pindah_pohon_kinerja = PindahPohonKinerja.create! valid_attributes
      get edit_pindah_pohon_kinerja_url(pindah_pohon_kinerja)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PindahPohonKinerja" do
        expect {
          post pindah_pohon_kinerjas_url, params: { pindah_pohon_kinerja: valid_attributes }
        }.to change(PindahPohonKinerja, :count).by(1)
      end

      it "redirects to the created pindah_pohon_kinerja" do
        post pindah_pohon_kinerjas_url, params: { pindah_pohon_kinerja: valid_attributes }
        expect(response).to redirect_to(pindah_pohon_kinerja_url(PindahPohonKinerja.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PindahPohonKinerja" do
        expect {
          post pindah_pohon_kinerjas_url, params: { pindah_pohon_kinerja: invalid_attributes }
        }.to change(PindahPohonKinerja, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post pindah_pohon_kinerjas_url, params: { pindah_pohon_kinerja: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pindah_pohon_kinerja" do
        pindah_pohon_kinerja = PindahPohonKinerja.create! valid_attributes
        patch pindah_pohon_kinerja_url(pindah_pohon_kinerja), params: { pindah_pohon_kinerja: new_attributes }
        pindah_pohon_kinerja.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the pindah_pohon_kinerja" do
        pindah_pohon_kinerja = PindahPohonKinerja.create! valid_attributes
        patch pindah_pohon_kinerja_url(pindah_pohon_kinerja), params: { pindah_pohon_kinerja: new_attributes }
        pindah_pohon_kinerja.reload
        expect(response).to redirect_to(pindah_pohon_kinerja_url(pindah_pohon_kinerja))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        pindah_pohon_kinerja = PindahPohonKinerja.create! valid_attributes
        patch pindah_pohon_kinerja_url(pindah_pohon_kinerja), params: { pindah_pohon_kinerja: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested pindah_pohon_kinerja" do
      pindah_pohon_kinerja = PindahPohonKinerja.create! valid_attributes
      expect {
        delete pindah_pohon_kinerja_url(pindah_pohon_kinerja)
      }.to change(PindahPohonKinerja, :count).by(-1)
    end

    it "redirects to the pindah_pohon_kinerjas list" do
      pindah_pohon_kinerja = PindahPohonKinerja.create! valid_attributes
      delete pindah_pohon_kinerja_url(pindah_pohon_kinerja)
      expect(response).to redirect_to(pindah_pohon_kinerjas_url)
    end
  end
end
