 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/pks", type: :request do
  
  # Pk. As you add validations to Pk, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Pk.create! valid_attributes
      get pks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      pk = Pk.create! valid_attributes
      get pk_url(pk)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_pk_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      pk = Pk.create! valid_attributes
      get edit_pk_url(pk)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Pk" do
        expect {
          post pks_url, params: { pk: valid_attributes }
        }.to change(Pk, :count).by(1)
      end

      it "redirects to the created pk" do
        post pks_url, params: { pk: valid_attributes }
        expect(response).to redirect_to(pk_url(Pk.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Pk" do
        expect {
          post pks_url, params: { pk: invalid_attributes }
        }.to change(Pk, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post pks_url, params: { pk: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pk" do
        pk = Pk.create! valid_attributes
        patch pk_url(pk), params: { pk: new_attributes }
        pk.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the pk" do
        pk = Pk.create! valid_attributes
        patch pk_url(pk), params: { pk: new_attributes }
        pk.reload
        expect(response).to redirect_to(pk_url(pk))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        pk = Pk.create! valid_attributes
        patch pk_url(pk), params: { pk: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested pk" do
      pk = Pk.create! valid_attributes
      expect {
        delete pk_url(pk)
      }.to change(Pk, :count).by(-1)
    end

    it "redirects to the pks list" do
      pk = Pk.create! valid_attributes
      delete pk_url(pk)
      expect(response).to redirect_to(pks_url)
    end
  end
end
