 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/pokpirs", type: :request do
  
  # Pokpir. As you add validations to Pokpir, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Pokpir.create! valid_attributes
      get pokpirs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      pokpir = Pokpir.create! valid_attributes
      get pokpir_url(pokpir)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_pokpir_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      pokpir = Pokpir.create! valid_attributes
      get edit_pokpir_url(pokpir)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Pokpir" do
        expect {
          post pokpirs_url, params: { pokpir: valid_attributes }
        }.to change(Pokpir, :count).by(1)
      end

      it "redirects to the created pokpir" do
        post pokpirs_url, params: { pokpir: valid_attributes }
        expect(response).to redirect_to(pokpir_url(Pokpir.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Pokpir" do
        expect {
          post pokpirs_url, params: { pokpir: invalid_attributes }
        }.to change(Pokpir, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post pokpirs_url, params: { pokpir: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pokpir" do
        pokpir = Pokpir.create! valid_attributes
        patch pokpir_url(pokpir), params: { pokpir: new_attributes }
        pokpir.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the pokpir" do
        pokpir = Pokpir.create! valid_attributes
        patch pokpir_url(pokpir), params: { pokpir: new_attributes }
        pokpir.reload
        expect(response).to redirect_to(pokpir_url(pokpir))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        pokpir = Pokpir.create! valid_attributes
        patch pokpir_url(pokpir), params: { pokpir: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested pokpir" do
      pokpir = Pokpir.create! valid_attributes
      expect {
        delete pokpir_url(pokpir)
      }.to change(Pokpir, :count).by(-1)
    end

    it "redirects to the pokpirs list" do
      pokpir = Pokpir.create! valid_attributes
      delete pokpir_url(pokpir)
      expect(response).to redirect_to(pokpirs_url)
    end
  end
end
