require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/program_unggulans", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ProgramUnggulan. As you add validations to ProgramUnggulan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProgramUnggulan.create! valid_attributes
      get program_unggulans_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      program_unggulan = ProgramUnggulan.create! valid_attributes
      get program_unggulan_url(program_unggulan)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_program_unggulan_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      program_unggulan = ProgramUnggulan.create! valid_attributes
      get edit_program_unggulan_url(program_unggulan)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProgramUnggulan" do
        expect {
          post program_unggulans_url, params: { program_unggulan: valid_attributes }
        }.to change(ProgramUnggulan, :count).by(1)
      end

      it "redirects to the created program_unggulan" do
        post program_unggulans_url, params: { program_unggulan: valid_attributes }
        expect(response).to redirect_to(program_unggulan_url(ProgramUnggulan.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProgramUnggulan" do
        expect {
          post program_unggulans_url, params: { program_unggulan: invalid_attributes }
        }.to change(ProgramUnggulan, :count).by(0)
      end

    
      it "renders a successful response (i.e. to display the 'new' template)" do
        post program_unggulans_url, params: { program_unggulan: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested program_unggulan" do
        program_unggulan = ProgramUnggulan.create! valid_attributes
        patch program_unggulan_url(program_unggulan), params: { program_unggulan: new_attributes }
        program_unggulan.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the program_unggulan" do
        program_unggulan = ProgramUnggulan.create! valid_attributes
        patch program_unggulan_url(program_unggulan), params: { program_unggulan: new_attributes }
        program_unggulan.reload
        expect(response).to redirect_to(program_unggulan_url(program_unggulan))
      end
    end

    context "with invalid parameters" do
    
      it "renders a successful response (i.e. to display the 'edit' template)" do
        program_unggulan = ProgramUnggulan.create! valid_attributes
        patch program_unggulan_url(program_unggulan), params: { program_unggulan: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested program_unggulan" do
      program_unggulan = ProgramUnggulan.create! valid_attributes
      expect {
        delete program_unggulan_url(program_unggulan)
      }.to change(ProgramUnggulan, :count).by(-1)
    end

    it "redirects to the program_unggulans list" do
      program_unggulan = ProgramUnggulan.create! valid_attributes
      delete program_unggulan_url(program_unggulan)
      expect(response).to redirect_to(program_unggulans_url)
    end
  end
end
