 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/rincians", type: :request do
  
  # Rincian. As you add validations to Rincian, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Rincian.create! valid_attributes
      get rincians_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      rincian = Rincian.create! valid_attributes
      get rincian_url(rincian)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_rincian_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      rincian = Rincian.create! valid_attributes
      get edit_rincian_url(rincian)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Rincian" do
        expect {
          post rincians_url, params: { rincian: valid_attributes }
        }.to change(Rincian, :count).by(1)
      end

      it "redirects to the created rincian" do
        post rincians_url, params: { rincian: valid_attributes }
        expect(response).to redirect_to(rincian_url(Rincian.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Rincian" do
        expect {
          post rincians_url, params: { rincian: invalid_attributes }
        }.to change(Rincian, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post rincians_url, params: { rincian: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested rincian" do
        rincian = Rincian.create! valid_attributes
        patch rincian_url(rincian), params: { rincian: new_attributes }
        rincian.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the rincian" do
        rincian = Rincian.create! valid_attributes
        patch rincian_url(rincian), params: { rincian: new_attributes }
        rincian.reload
        expect(response).to redirect_to(rincian_url(rincian))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        rincian = Rincian.create! valid_attributes
        patch rincian_url(rincian), params: { rincian: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested rincian" do
      rincian = Rincian.create! valid_attributes
      expect {
        delete rincian_url(rincian)
      }.to change(Rincian, :count).by(-1)
    end

    it "redirects to the rincians list" do
      rincian = Rincian.create! valid_attributes
      delete rincian_url(rincian)
      expect(response).to redirect_to(rincians_url)
    end
  end
end
