require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sasaran_opds", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SasaranOpd. As you add validations to SasaranOpd, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SasaranOpd.create! valid_attributes
      get sasaran_opds_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sasaran_opd = SasaranOpd.create! valid_attributes
      get sasaran_opd_url(sasaran_opd)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sasaran_opd_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      sasaran_opd = SasaranOpd.create! valid_attributes
      get edit_sasaran_opd_url(sasaran_opd)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SasaranOpd" do
        expect {
          post sasaran_opds_url, params: { sasaran_opd: valid_attributes }
        }.to change(SasaranOpd, :count).by(1)
      end

      it "redirects to the created sasaran_opd" do
        post sasaran_opds_url, params: { sasaran_opd: valid_attributes }
        expect(response).to redirect_to(sasaran_opd_url(SasaranOpd.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SasaranOpd" do
        expect {
          post sasaran_opds_url, params: { sasaran_opd: invalid_attributes }
        }.to change(SasaranOpd, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post sasaran_opds_url, params: { sasaran_opd: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sasaran_opd" do
        sasaran_opd = SasaranOpd.create! valid_attributes
        patch sasaran_opd_url(sasaran_opd), params: { sasaran_opd: new_attributes }
        sasaran_opd.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the sasaran_opd" do
        sasaran_opd = SasaranOpd.create! valid_attributes
        patch sasaran_opd_url(sasaran_opd), params: { sasaran_opd: new_attributes }
        sasaran_opd.reload
        expect(response).to redirect_to(sasaran_opd_url(sasaran_opd))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        sasaran_opd = SasaranOpd.create! valid_attributes
        patch sasaran_opd_url(sasaran_opd), params: { sasaran_opd: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sasaran_opd" do
      sasaran_opd = SasaranOpd.create! valid_attributes
      expect {
        delete sasaran_opd_url(sasaran_opd)
      }.to change(SasaranOpd, :count).by(-1)
    end

    it "redirects to the sasaran_opds list" do
      sasaran_opd = SasaranOpd.create! valid_attributes
      delete sasaran_opd_url(sasaran_opd)
      expect(response).to redirect_to(sasaran_opds_url)
    end
  end
end
