 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sasarans", type: :request do
  
  # Sasaran. As you add validations to Sasaran, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Sasaran.create! valid_attributes
      get sasarans_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sasaran = Sasaran.create! valid_attributes
      get sasaran_url(sasaran)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sasaran_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      sasaran = Sasaran.create! valid_attributes
      get edit_sasaran_url(sasaran)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Sasaran" do
        expect {
          post sasarans_url, params: { sasaran: valid_attributes }
        }.to change(Sasaran, :count).by(1)
      end

      it "redirects to the created sasaran" do
        post sasarans_url, params: { sasaran: valid_attributes }
        expect(response).to redirect_to(sasaran_url(Sasaran.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Sasaran" do
        expect {
          post sasarans_url, params: { sasaran: invalid_attributes }
        }.to change(Sasaran, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post sasarans_url, params: { sasaran: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sasaran" do
        sasaran = Sasaran.create! valid_attributes
        patch sasaran_url(sasaran), params: { sasaran: new_attributes }
        sasaran.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the sasaran" do
        sasaran = Sasaran.create! valid_attributes
        patch sasaran_url(sasaran), params: { sasaran: new_attributes }
        sasaran.reload
        expect(response).to redirect_to(sasaran_url(sasaran))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        sasaran = Sasaran.create! valid_attributes
        patch sasaran_url(sasaran), params: { sasaran: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sasaran" do
      sasaran = Sasaran.create! valid_attributes
      expect {
        delete sasaran_url(sasaran)
      }.to change(Sasaran, :count).by(-1)
    end

    it "redirects to the sasarans list" do
      sasaran = Sasaran.create! valid_attributes
      delete sasaran_url(sasaran)
      expect(response).to redirect_to(sasarans_url)
    end
  end
end
