require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/skalas", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Skala. As you add validations to Skala, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Skala.create! valid_attributes
      get skalas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      skala = Skala.create! valid_attributes
      get skala_url(skala)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_skala_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      skala = Skala.create! valid_attributes
      get edit_skala_url(skala)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Skala" do
        expect {
          post skalas_url, params: { skala: valid_attributes }
        }.to change(Skala, :count).by(1)
      end

      it "redirects to the created skala" do
        post skalas_url, params: { skala: valid_attributes }
        expect(response).to redirect_to(skala_url(Skala.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Skala" do
        expect {
          post skalas_url, params: { skala: invalid_attributes }
        }.to change(Skala, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post skalas_url, params: { skala: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested skala" do
        skala = Skala.create! valid_attributes
        patch skala_url(skala), params: { skala: new_attributes }
        skala.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the skala" do
        skala = Skala.create! valid_attributes
        patch skala_url(skala), params: { skala: new_attributes }
        skala.reload
        expect(response).to redirect_to(skala_url(skala))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        skala = Skala.create! valid_attributes
        patch skala_url(skala), params: { skala: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested skala" do
      skala = Skala.create! valid_attributes
      expect {
        delete skala_url(skala)
      }.to change(Skala, :count).by(-1)
    end

    it "redirects to the skalas list" do
      skala = Skala.create! valid_attributes
      delete skala_url(skala)
      expect(response).to redirect_to(skalas_url)
    end
  end
end
