require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/strategi_opds", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # StrategiOpd. As you add validations to StrategiOpd, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      StrategiOpd.create! valid_attributes
      get strategi_opds_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      strategi_opd = StrategiOpd.create! valid_attributes
      get strategi_opd_url(strategi_opd)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_strategi_opd_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      strategi_opd = StrategiOpd.create! valid_attributes
      get edit_strategi_opd_url(strategi_opd)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new StrategiOpd" do
        expect {
          post strategi_opds_url, params: { strategi_opd: valid_attributes }
        }.to change(StrategiOpd, :count).by(1)
      end

      it "redirects to the created strategi_opd" do
        post strategi_opds_url, params: { strategi_opd: valid_attributes }
        expect(response).to redirect_to(strategi_opd_url(StrategiOpd.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new StrategiOpd" do
        expect {
          post strategi_opds_url, params: { strategi_opd: invalid_attributes }
        }.to change(StrategiOpd, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post strategi_opds_url, params: { strategi_opd: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested strategi_opd" do
        strategi_opd = StrategiOpd.create! valid_attributes
        patch strategi_opd_url(strategi_opd), params: { strategi_opd: new_attributes }
        strategi_opd.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the strategi_opd" do
        strategi_opd = StrategiOpd.create! valid_attributes
        patch strategi_opd_url(strategi_opd), params: { strategi_opd: new_attributes }
        strategi_opd.reload
        expect(response).to redirect_to(strategi_opd_url(strategi_opd))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        strategi_opd = StrategiOpd.create! valid_attributes
        patch strategi_opd_url(strategi_opd), params: { strategi_opd: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested strategi_opd" do
      strategi_opd = StrategiOpd.create! valid_attributes
      expect {
        delete strategi_opd_url(strategi_opd)
      }.to change(StrategiOpd, :count).by(-1)
    end

    it "redirects to the strategi_opds list" do
      strategi_opd = StrategiOpd.create! valid_attributes
      delete strategi_opd_url(strategi_opd)
      expect(response).to redirect_to(strategi_opds_url)
    end
  end
end
