require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/strategi_arah_kebijakans", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # StrategiArahKebijakan. As you add validations to StrategiArahKebijakan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      StrategiArahKebijakan.create! valid_attributes
      get strategi_arah_kebijakans_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      strategi_arah_kebijakan = StrategiArahKebijakan.create! valid_attributes
      get strategi_arah_kebijakan_url(strategi_arah_kebijakan)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_strategi_arah_kebijakan_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      strategi_arah_kebijakan = StrategiArahKebijakan.create! valid_attributes
      get edit_strategi_arah_kebijakan_url(strategi_arah_kebijakan)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new StrategiArahKebijakan" do
        expect {
          post strategi_arah_kebijakans_url, params: { strategi_arah_kebijakan: valid_attributes }
        }.to change(StrategiArahKebijakan, :count).by(1)
      end

      it "redirects to the created strategi_arah_kebijakan" do
        post strategi_arah_kebijakans_url, params: { strategi_arah_kebijakan: valid_attributes }
        expect(response).to redirect_to(strategi_arah_kebijakan_url(StrategiArahKebijakan.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new StrategiArahKebijakan" do
        expect {
          post strategi_arah_kebijakans_url, params: { strategi_arah_kebijakan: invalid_attributes }
        }.to change(StrategiArahKebijakan, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post strategi_arah_kebijakans_url, params: { strategi_arah_kebijakan: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested strategi_arah_kebijakan" do
        strategi_arah_kebijakan = StrategiArahKebijakan.create! valid_attributes
        patch strategi_arah_kebijakan_url(strategi_arah_kebijakan), params: { strategi_arah_kebijakan: new_attributes }
        strategi_arah_kebijakan.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the strategi_arah_kebijakan" do
        strategi_arah_kebijakan = StrategiArahKebijakan.create! valid_attributes
        patch strategi_arah_kebijakan_url(strategi_arah_kebijakan), params: { strategi_arah_kebijakan: new_attributes }
        strategi_arah_kebijakan.reload
        expect(response).to redirect_to(strategi_arah_kebijakan_url(strategi_arah_kebijakan))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        strategi_arah_kebijakan = StrategiArahKebijakan.create! valid_attributes
        patch strategi_arah_kebijakan_url(strategi_arah_kebijakan), params: { strategi_arah_kebijakan: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested strategi_arah_kebijakan" do
      strategi_arah_kebijakan = StrategiArahKebijakan.create! valid_attributes
      expect {
        delete strategi_arah_kebijakan_url(strategi_arah_kebijakan)
      }.to change(StrategiArahKebijakan, :count).by(-1)
    end

    it "redirects to the strategi_arah_kebijakans list" do
      strategi_arah_kebijakan = StrategiArahKebijakan.create! valid_attributes
      delete strategi_arah_kebijakan_url(strategi_arah_kebijakan)
      expect(response).to redirect_to(strategi_arah_kebijakans_url)
    end
  end
end
