 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/subkegiatan_tematiks", type: :request do
  
  # SubkegiatanTematik. As you add validations to SubkegiatanTematik, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SubkegiatanTematik.create! valid_attributes
      get subkegiatan_tematiks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      subkegiatan_tematik = SubkegiatanTematik.create! valid_attributes
      get subkegiatan_tematik_url(subkegiatan_tematik)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_subkegiatan_tematik_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      subkegiatan_tematik = SubkegiatanTematik.create! valid_attributes
      get edit_subkegiatan_tematik_url(subkegiatan_tematik)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SubkegiatanTematik" do
        expect {
          post subkegiatan_tematiks_url, params: { subkegiatan_tematik: valid_attributes }
        }.to change(SubkegiatanTematik, :count).by(1)
      end

      it "redirects to the created subkegiatan_tematik" do
        post subkegiatan_tematiks_url, params: { subkegiatan_tematik: valid_attributes }
        expect(response).to redirect_to(subkegiatan_tematik_url(SubkegiatanTematik.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SubkegiatanTematik" do
        expect {
          post subkegiatan_tematiks_url, params: { subkegiatan_tematik: invalid_attributes }
        }.to change(SubkegiatanTematik, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post subkegiatan_tematiks_url, params: { subkegiatan_tematik: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested subkegiatan_tematik" do
        subkegiatan_tematik = SubkegiatanTematik.create! valid_attributes
        patch subkegiatan_tematik_url(subkegiatan_tematik), params: { subkegiatan_tematik: new_attributes }
        subkegiatan_tematik.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the subkegiatan_tematik" do
        subkegiatan_tematik = SubkegiatanTematik.create! valid_attributes
        patch subkegiatan_tematik_url(subkegiatan_tematik), params: { subkegiatan_tematik: new_attributes }
        subkegiatan_tematik.reload
        expect(response).to redirect_to(subkegiatan_tematik_url(subkegiatan_tematik))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        subkegiatan_tematik = SubkegiatanTematik.create! valid_attributes
        patch subkegiatan_tematik_url(subkegiatan_tematik), params: { subkegiatan_tematik: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested subkegiatan_tematik" do
      subkegiatan_tematik = SubkegiatanTematik.create! valid_attributes
      expect {
        delete subkegiatan_tematik_url(subkegiatan_tematik)
      }.to change(SubkegiatanTematik, :count).by(-1)
    end

    it "redirects to the subkegiatan_tematiks list" do
      subkegiatan_tematik = SubkegiatanTematik.create! valid_attributes
      delete subkegiatan_tematik_url(subkegiatan_tematik)
      expect(response).to redirect_to(subkegiatan_tematiks_url)
    end
  end
end
