require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tagging_anggarans", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # TaggingAnggaran. As you add validations to TaggingAnggaran, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TaggingAnggaran.create! valid_attributes
      get tagging_anggarans_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tagging_anggaran = TaggingAnggaran.create! valid_attributes
      get tagging_anggaran_url(tagging_anggaran)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tagging_anggaran_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      tagging_anggaran = TaggingAnggaran.create! valid_attributes
      get edit_tagging_anggaran_url(tagging_anggaran)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TaggingAnggaran" do
        expect {
          post tagging_anggarans_url, params: { tagging_anggaran: valid_attributes }
        }.to change(TaggingAnggaran, :count).by(1)
      end

      it "redirects to the created tagging_anggaran" do
        post tagging_anggarans_url, params: { tagging_anggaran: valid_attributes }
        expect(response).to redirect_to(tagging_anggaran_url(TaggingAnggaran.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TaggingAnggaran" do
        expect {
          post tagging_anggarans_url, params: { tagging_anggaran: invalid_attributes }
        }.to change(TaggingAnggaran, :count).by(0)
      end

    
      it "renders a successful response (i.e. to display the 'new' template)" do
        post tagging_anggarans_url, params: { tagging_anggaran: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tagging_anggaran" do
        tagging_anggaran = TaggingAnggaran.create! valid_attributes
        patch tagging_anggaran_url(tagging_anggaran), params: { tagging_anggaran: new_attributes }
        tagging_anggaran.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tagging_anggaran" do
        tagging_anggaran = TaggingAnggaran.create! valid_attributes
        patch tagging_anggaran_url(tagging_anggaran), params: { tagging_anggaran: new_attributes }
        tagging_anggaran.reload
        expect(response).to redirect_to(tagging_anggaran_url(tagging_anggaran))
      end
    end

    context "with invalid parameters" do
    
      it "renders a successful response (i.e. to display the 'edit' template)" do
        tagging_anggaran = TaggingAnggaran.create! valid_attributes
        patch tagging_anggaran_url(tagging_anggaran), params: { tagging_anggaran: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tagging_anggaran" do
      tagging_anggaran = TaggingAnggaran.create! valid_attributes
      expect {
        delete tagging_anggaran_url(tagging_anggaran)
      }.to change(TaggingAnggaran, :count).by(-1)
    end

    it "redirects to the tagging_anggarans list" do
      tagging_anggaran = TaggingAnggaran.create! valid_attributes
      delete tagging_anggaran_url(tagging_anggaran)
      expect(response).to redirect_to(tagging_anggarans_url)
    end
  end
end
