 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tahapans", type: :request do
  
  # Tahapan. As you add validations to Tahapan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Tahapan.create! valid_attributes
      get tahapans_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tahapan = Tahapan.create! valid_attributes
      get tahapan_url(tahapan)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tahapan_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      tahapan = Tahapan.create! valid_attributes
      get edit_tahapan_url(tahapan)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Tahapan" do
        expect {
          post tahapans_url, params: { tahapan: valid_attributes }
        }.to change(Tahapan, :count).by(1)
      end

      it "redirects to the created tahapan" do
        post tahapans_url, params: { tahapan: valid_attributes }
        expect(response).to redirect_to(tahapan_url(Tahapan.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Tahapan" do
        expect {
          post tahapans_url, params: { tahapan: invalid_attributes }
        }.to change(Tahapan, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post tahapans_url, params: { tahapan: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tahapan" do
        tahapan = Tahapan.create! valid_attributes
        patch tahapan_url(tahapan), params: { tahapan: new_attributes }
        tahapan.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tahapan" do
        tahapan = Tahapan.create! valid_attributes
        patch tahapan_url(tahapan), params: { tahapan: new_attributes }
        tahapan.reload
        expect(response).to redirect_to(tahapan_url(tahapan))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        tahapan = Tahapan.create! valid_attributes
        patch tahapan_url(tahapan), params: { tahapan: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tahapan" do
      tahapan = Tahapan.create! valid_attributes
      expect {
        delete tahapan_url(tahapan)
      }.to change(Tahapan, :count).by(-1)
    end

    it "redirects to the tahapans list" do
      tahapan = Tahapan.create! valid_attributes
      delete tahapan_url(tahapan)
      expect(response).to redirect_to(tahapans_url)
    end
  end
end
