require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tematiks", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Tematik. As you add validations to Tematik, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Tematik.create! valid_attributes
      get tematiks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tematik = Tematik.create! valid_attributes
      get tematik_url(tematik)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tematik_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      tematik = Tematik.create! valid_attributes
      get edit_tematik_url(tematik)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Tematik" do
        expect {
          post tematiks_url, params: { tematik: valid_attributes }
        }.to change(Tematik, :count).by(1)
      end

      it "redirects to the created tematik" do
        post tematiks_url, params: { tematik: valid_attributes }
        expect(response).to redirect_to(tematik_url(Tematik.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Tematik" do
        expect {
          post tematiks_url, params: { tematik: invalid_attributes }
        }.to change(Tematik, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post tematiks_url, params: { tematik: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tematik" do
        tematik = Tematik.create! valid_attributes
        patch tematik_url(tematik), params: { tematik: new_attributes }
        tematik.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tematik" do
        tematik = Tematik.create! valid_attributes
        patch tematik_url(tematik), params: { tematik: new_attributes }
        tematik.reload
        expect(response).to redirect_to(tematik_url(tematik))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        tematik = Tematik.create! valid_attributes
        patch tematik_url(tematik), params: { tematik: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tematik" do
      tematik = Tematik.create! valid_attributes
      expect {
        delete tematik_url(tematik)
      }.to change(Tematik, :count).by(-1)
    end

    it "redirects to the tematiks list" do
      tematik = Tematik.create! valid_attributes
      delete tematik_url(tematik)
      expect(response).to redirect_to(tematiks_url)
    end
  end
end
