require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tte_documents", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # TteDocument. As you add validations to TteDocument, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TteDocument.create! valid_attributes
      get tte_documents_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tte_document = TteDocument.create! valid_attributes
      get tte_document_url(tte_document)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tte_document_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      tte_document = TteDocument.create! valid_attributes
      get edit_tte_document_url(tte_document)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TteDocument" do
        expect {
          post tte_documents_url, params: { tte_document: valid_attributes }
        }.to change(TteDocument, :count).by(1)
      end

      it "redirects to the created tte_document" do
        post tte_documents_url, params: { tte_document: valid_attributes }
        expect(response).to redirect_to(tte_document_url(TteDocument.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TteDocument" do
        expect {
          post tte_documents_url, params: { tte_document: invalid_attributes }
        }.to change(TteDocument, :count).by(0)
      end

    
      it "renders a successful response (i.e. to display the 'new' template)" do
        post tte_documents_url, params: { tte_document: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tte_document" do
        tte_document = TteDocument.create! valid_attributes
        patch tte_document_url(tte_document), params: { tte_document: new_attributes }
        tte_document.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tte_document" do
        tte_document = TteDocument.create! valid_attributes
        patch tte_document_url(tte_document), params: { tte_document: new_attributes }
        tte_document.reload
        expect(response).to redirect_to(tte_document_url(tte_document))
      end
    end

    context "with invalid parameters" do
    
      it "renders a successful response (i.e. to display the 'edit' template)" do
        tte_document = TteDocument.create! valid_attributes
        patch tte_document_url(tte_document), params: { tte_document: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tte_document" do
      tte_document = TteDocument.create! valid_attributes
      expect {
        delete tte_document_url(tte_document)
      }.to change(TteDocument, :count).by(-1)
    end

    it "redirects to the tte_documents list" do
      tte_document = TteDocument.create! valid_attributes
      delete tte_document_url(tte_document)
      expect(response).to redirect_to(tte_documents_url)
    end
  end
end
