# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  hostname: <%= ENV.fetch("DATABASE_URL") { 'localhost' } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { 'ekak_kota_madiun_dev' } %>

test:
  <<: *default
  database: ekak_kota_madiun_test

production:
  <<: *default
  database: ekak_kota_madiun_prod
